<?php

require __DIR__ . '/../vendor/autoload.php';

use Uteek\LogTracker\LogTrackerClient;

echo "\n========================================\n";
echo "  UTEEK Log Tracker SDK v1 – Basic Test\n";
echo "========================================\n\n";

// The api_key is generated by the UTEEK monitoring dashboard when you create a project.
// It is sent in the X-API-Key header on every request to the Node.js ingest server;
// it is never included in the log payload body.
$client = new LogTrackerClient([
    'api_url'     => 'http://localhost:3000',       // Node.js ingest server
    'api_key'     => 'ltk_6gAlGqDZvcgS3LsCaavVwHXHm0MYMzBKrHI0yi6qIdk0GYTnhz3zutDY5s08',  // from monitoring dashboard
    'project_id'  => '4',                 // from monitoring dashboard
    'environment' => 'development',
    'log_levels'  => ['debug', 'info', 'warning', 'error', 'critical'],
    'debug'       => true,  // throws on auth failure in dev; remove in production
]);

// ─── 0. Verify API key against the Node.js backend ───────────────────────────
echo "[0/4] Verifying API key with the ingest server...\n";
if (!$client->ping()) {
    echo "      [FAIL] API key rejected. Check your UTEEK monitoring dashboard.\n\n";
    exit(1);
}
echo "      [OK] API key accepted\n\n";

// ─── 1. Register global handlers ─────────────────────────────────────────────
echo "[1/4] Registering error & exception handlers...\n";
$client->registerErrorHandler();
$client->registerExceptionHandler();
echo "      [OK] handlers registered\n\n";

// ─── 2. Attach user context ───────────────────────────────────────────────────
$client->setUser(['id' => 42, 'email' => 'john@example.com']);

// ─── 3. Log all levels ────────────────────────────────────────────────────────
echo "[2/4] Sending logs at all levels...\n";
$client->debug('Cache lookup',   ['key' => 'user:42']);
$client->info('User logged in',  ['username' => 'john']);
$client->warning('Slow query',   ['duration_ms' => 850]);
$client->error('DB connection failed', ['code' => 1045]);
$client->critical('Disk full',   ['path' => '/var/www']);
echo "      [OK] 5 logs buffered\n\n";

// ─── 4. Capture an exception ─────────────────────────────────────────────────
echo "[3/4] Capturing exception...\n";
try {
    throw new RuntimeException('Payment gateway timeout', 504);
} catch (Exception $e) {
    $client->captureException($e, ['order_id' => 99, 'extra_context' => 'Payment processing']);
}
echo "      [OK] exception captured\n\n";

// ─── 5. Flush to Node.js ─────────────────────────────────────────────────────
echo "[4/4] Flushing batch to Node.js ingest server...\n";
$client->flush();
echo "      [OK] flushed\n\n";

echo "========================================\n";
echo "  SUCCESS!\n";
echo "========================================\n\n";

